//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcmp2.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mcmp2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bin {
            get {
                object obj = ResourceManager.GetObject("bin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bin_1 {
            get {
                object obj = ResourceManager.GetObject("bin-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo2 {
            get {
                object obj = ResourceManager.GetObject("logo2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logoMCMP {
            get {
                object obj = ResourceManager.GetObject("logoMCMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription Impossible.
        /// </summary>
        internal static string TITRE_AGE {
            get {
                return ResourceManager.GetString("TITRE_AGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de saisie.
        /// </summary>
        internal static string TITRE_CHAMPOBLIGATOIRE {
            get {
                return ResourceManager.GetString("TITRE_CHAMPOBLIGATOIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Doublon sur date d&apos;activité.
        /// </summary>
        internal static string TITRE_DEJAINSCRIT {
            get {
                return ResourceManager.GetString("TITRE_DEJAINSCRIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date limite dépassée.
        /// </summary>
        internal static string TITRE_DLIMITE {
            get {
                return ResourceManager.GetString("TITRE_DLIMITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de création.
        /// </summary>
        internal static string TITRE_ERRADD {
            get {
                return ResourceManager.GetString("TITRE_ERRADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de création Adhérent.
        /// </summary>
        internal static string TITRE_ERRADDAD {
            get {
                return ResourceManager.GetString("TITRE_ERRADDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attention doublon.
        /// </summary>
        internal static string TITRE_ERRDOUBL {
            get {
                return ResourceManager.GetString("TITRE_ERRDOUBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de modification.
        /// </summary>
        internal static string TITRE_ERRMODIF {
            get {
                return ResourceManager.GetString("TITRE_ERRMODIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de supression.
        /// </summary>
        internal static string TITRE_ERRSUPP {
            get {
                return ResourceManager.GetString("TITRE_ERRSUPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajout d&apos;un adhérent.
        /// </summary>
        internal static string TITRE_OKAJOUT {
            get {
                return ResourceManager.GetString("TITRE_OKAJOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription.
        /// </summary>
        internal static string TITRE_OKAJOUTINSCRIPTION {
            get {
                return ResourceManager.GetString("TITRE_OKAJOUTINSCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification.
        /// </summary>
        internal static string TITRE_OKMODIF {
            get {
                return ResourceManager.GetString("TITRE_OKMODIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression.
        /// </summary>
        internal static string TITRE_OKSUP {
            get {
                return ResourceManager.GetString("TITRE_OKSUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plus de place.
        /// </summary>
        internal static string TITRE_PARTICIPANTMAX {
            get {
                return ResourceManager.GetString("TITRE_PARTICIPANTMAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer &apos;{0} {1}&apos;.
        /// </summary>
        internal static string TITRE_SUPP {
            get {
                return ResourceManager.GetString("TITRE_SUPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression impossible.
        /// </summary>
        internal static string TITRE_SUPPIMPOSSIBLE {
            get {
                return ResourceManager.GetString("TITRE_SUPPIMPOSSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer inscription.
        /// </summary>
        internal static string TITRE_SUPPINSCR {
            get {
                return ResourceManager.GetString("TITRE_SUPPINSCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Désolé, l&apos;age minimum pour adhérer à l&apos;association est de 16 ans.
        /// </summary>
        internal static string TXT_AGE {
            get {
                return ResourceManager.GetString("TXT_AGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir les champs nécéssaires.
        /// </summary>
        internal static string TXT_CHAMPOBLIGATOIRE {
            get {
                return ResourceManager.GetString("TXT_CHAMPOBLIGATOIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet adhérent est déjà inscrit à une activité ce jour là.
        /// </summary>
        internal static string TXT_DEJAINSCRIT {
            get {
                return ResourceManager.GetString("TXT_DEJAINSCRIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Désolé, la date limite d&apos;inscription est passée.
        /// </summary>
        internal static string TXT_DLIMITE {
            get {
                return ResourceManager.GetString("TXT_DLIMITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;ajout n&apos;a pas été réalisé..
        /// </summary>
        internal static string TXT_ERRADD {
            get {
                return ResourceManager.GetString("TXT_ERRADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;ajout de l&apos;adhérent n&apos;a pas été réalisé..
        /// </summary>
        internal static string TXT_ERRADDAD {
            get {
                return ResourceManager.GetString("TXT_ERRADDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;utilisateur &apos;{0} {1}&apos; esiste dèja !.
        /// </summary>
        internal static string TXT_ERRDOUBL {
            get {
                return ResourceManager.GetString("TXT_ERRDOUBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La modification n&apos;a pas été réalisée..
        /// </summary>
        internal static string TXT_ERRMODIF {
            get {
                return ResourceManager.GetString("TXT_ERRMODIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La suppression n&apos;a pas été réalisée..
        /// </summary>
        internal static string TXT_ERRSUPP {
            get {
                return ResourceManager.GetString("TXT_ERRSUPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adhérent &apos;{0} {1}&apos; a été ajouté avec succes.
        /// </summary>
        internal static string TXT_OKAJOUT {
            get {
                return ResourceManager.GetString("TXT_OKAJOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adhérent &apos;{0} {1}&apos; a été inscrit avec succes à l&apos;activité&apos;{2}&apos;.
        /// </summary>
        internal static string TXT_OKAJOUTINSCRIPTION {
            get {
                return ResourceManager.GetString("TXT_OKAJOUTINSCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adhérent : &apos;{0}&apos; a été inscrit avec succes à l&apos;activité&apos;{1}&apos;.
        /// </summary>
        internal static string TXT_OKAJOUTINSCRIPTION2 {
            get {
                return ResourceManager.GetString("TXT_OKAJOUTINSCRIPTION2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adhérent &apos;{0} {1}&apos; a été modifié avec succes.
        /// </summary>
        internal static string TXT_OKMODIF {
            get {
                return ResourceManager.GetString("TXT_OKMODIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adhérent &apos;{0} {1}&apos; a été supprimé avec succes.
        /// </summary>
        internal static string TXT_OKSUP {
            get {
                return ResourceManager.GetString("TXT_OKSUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Désolé, le nombre maximal de participants est atteint.
        /// </summary>
        internal static string TXT_PARTICIPANTMAX {
            get {
                return ResourceManager.GetString("TXT_PARTICIPANTMAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez vous procéder à la suppression de &apos;{0} {1}&apos; ?.
        /// </summary>
        internal static string TXT_SUPP {
            get {
                return ResourceManager.GetString("TXT_SUPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La suppression de l&apos;adhérent &apos;{0} {1}&apos; est impossible, veuillez vérifier si il / elle ne participe pas à une activité..
        /// </summary>
        internal static string TXT_SUPPIMPOSSIBLE {
            get {
                return ResourceManager.GetString("TXT_SUPPIMPOSSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adhérent &apos;{0} {1}&apos; a été désinscrit avec succes de l&apos;activité &apos;{2}&apos;.
        /// </summary>
        internal static string TXT_SUPPINSCR {
            get {
                return ResourceManager.GetString("TXT_SUPPINSCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes vous sur de vouloir désinscrire &apos;{0} {1}&apos; de l&apos;activité &apos;{2}&apos;.
        /// </summary>
        internal static string TXT_SUPPINSCR2 {
            get {
                return ResourceManager.GetString("TXT_SUPPINSCR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format de numéro de téléphone n&apos;est pas valide.
        /// </summary>
        internal static string TXT_TEL {
            get {
                return ResourceManager.GetString("TXT_TEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format du code postal est incorrect.
        /// </summary>
        internal static string TXT_VALCP {
            get {
                return ResourceManager.GetString("TXT_VALCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir un email valide.
        /// </summary>
        internal static string TXT_VALEMAIL {
            get {
                return ResourceManager.GetString("TXT_VALEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir un nom.
        /// </summary>
        internal static string TXT_VALNOM {
            get {
                return ResourceManager.GetString("TXT_VALNOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir un prenom.
        /// </summary>
        internal static string TXT_VALPRENOM {
            get {
                return ResourceManager.GetString("TXT_VALPRENOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap video_game_monitor {
            get {
                object obj = ResourceManager.GetObject("video-game-monitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
